// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskGroupType string

const (
	TaskGroupTypeDay    TaskGroupType = "day"
	TaskGroupTypeWeek   TaskGroupType = "week"
	TaskGroupTypeMonth  TaskGroupType = "month"
	TaskGroupTypeYear   TaskGroupType = "year"
	TaskGroupTypeCustom TaskGroupType = "custom"
)

func (e *TaskGroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskGroupType(s)
	case string:
		*e = TaskGroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskGroupType: %T", src)
	}
	return nil
}

type NullTaskGroupType struct {
	TaskGroupType TaskGroupType `json:"task_group_type"`
	Valid         bool          `json:"valid"` // Valid is true if TaskGroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskGroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskGroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskGroupType), nil
}

type TaskStatus string

const (
	TaskStatusTodo    TaskStatus = "todo"
	TaskStatusDone    TaskStatus = "done"
	TaskStatusAbandon TaskStatus = "abandon"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

// 存储所有上传文件的元数据，如图片、视频、音频等
type Attachment struct {
	// 附件的唯一标识符 (UUID)
	ID pgtype.UUID `json:"id"`
	// 文件在 MinIO 中的唯一存储键 (路径/名称)
	ObjectKey string `json:"object_key"`
	// 文件的原始名称
	OriginalName   string `json:"original_name"`
	CoverObjectKey string `json:"cover_object_key"`
	// 文件的媒体类型 (e.g., image/jpeg)
	MimeType string `json:"mime_type"`
	// 文件内容的 MD5 哈希值，用于验证文件完整性
	Md5      string `json:"md5"`
	CoverMd5 string `json:"cover_md5"`
	// 文件大小（字节）
	FileSize int64 `json:"file_size"`
	// 文件上传状态 (e.g., uploading, completed, failed)
	Status string `json:"status"`
	// 记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	// 事件的唯一标识符
	ID int64 `json:"id"`
	// 事件的名称
	Name string `json:"name"`
	// 事件的地点
	Place string `json:"place"`
	// 事件的描述
	Description string `json:"description"`
	// 事件的开始时间
	StartTime pgtype.Timestamptz `json:"start_time"`
	// 事件的结束时间
	EndTime pgtype.Timestamptz `json:"end_time"`
	// 记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 事件提醒表
type EventReminder struct {
	// 主键，自增ID
	ID int64 `json:"id"`
	// 关联的事件ID
	EventID int64 `json:"event_id"`
	// 提醒前的时间间隔（单位：分）
	RemindBefore int32 `json:"remind_before"`
	// 是否已通知
	Notified bool `json:"notified"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 习惯表
type Habit struct {
	// 习惯的唯一标识符
	ID int64 `json:"id"`
	// 习惯的名称
	Name string `json:"name"`
	// 习惯的描述
	Description string `json:"description"`
	// 记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 习惯日志表
type HabitLog struct {
	// 习惯日志的唯一标识符
	ID int64 `json:"id"`
	// 习惯的唯一标识符
	HabitID int64 `json:"habit_id"`
	// 发生时间
	HappenedAt pgtype.Timestamptz `json:"happened_at"`
}

// 用于存储即使信息，包括文本内容和附件
type Moment struct {
	// 备忘录的唯一标识符
	ID int64 `json:"id"`
	// 备忘录的主要文本内容
	Content string `json:"content"`
	// 记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 连接 moments 和 attachments 的多对多联结表
type MomentAttachment struct {
	// 联结记录的唯一标识符
	ID int64 `json:"id"`
	// 关联的 Moment ID
	MomentID int64 `json:"moment_id"`
	// 关联的附件 ID
	AttachmentID pgtype.UUID `json:"attachment_id"`
	// 附件在 Moment 中的显示顺序 (0-8)
	Position int16 `json:"position"`
}

// 任务表，存储具体的任务信息
type Task struct {
	// 主键，自增ID
	ID int64 `json:"id"`
	// 所属任务组ID，外键关联task_groups表
	GroupID int64 `json:"group_id"`
	// 任务内容
	Content string `json:"content"`
	// 任务状态：todo(待办), done(完成), abandon(放弃)
	Status TaskStatus `json:"status"`
	// 任务截止时间
	Deadline pgtype.Timestamptz `json:"deadline"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 任务分组表，仅可保存年任务组(2025)，月任务组(2025-07)，周任务组(2025-W28)，日任务组(2025-07-14)
type TaskGroup struct {
	// 主键，自增ID
	ID int64 `json:"id"`
	// 任务分组名称
	Name string `json:"name"`
	// 任务分组描述
	Description string `json:"description"`
	// 任务分组类型：day(日), week(周), month(月), year(年), custom(自定义)
	Type TaskGroupType `json:"type"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 用户表，存储用户基本信息
type User struct {
	// 主键，自增ID
	ID int64 `json:"id"`
	// 用户邮箱，唯一标识
	Email string `json:"email"`
	// 用户姓名
	Name string `json:"name"`
	// 密码哈希值
	PasswordHash string `json:"password_hash"`
	// 用户生日
	Birthday pgtype.Date `json:"birthday"`
	// 头像Base64编码数据
	AvatarBase64 string `json:"avatar_base64"`
	// 用户简介
	Bio string `json:"bio"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
