// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (group_id, content, deadline)
VALUES ($1, $2, $3)
RETURNING id, group_id, content, status, deadline, created_at, updated_at
`

type CreateTaskParams struct {
	GroupID  int64              `json:"group_id"`
	Content  string             `json:"content"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.GroupID, arg.Content, arg.Deadline)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Content,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskById = `-- name: DeleteTaskById :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTaskById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTaskById, id)
	return err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, group_id, content, status, deadline, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Content,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByGroupId = `-- name: GetTasksByGroupId :many
SELECT id, group_id, content, status, deadline, created_at, updated_at FROM tasks
WHERE group_id = $1
ORDER BY
    CASE WHEN deadline IS NULL THEN 1 ELSE 0 END,
    CASE WHEN deadline < NOW() THEN 0 ELSE 1 END,
    deadline ASC
`

func (q *Queries) GetTasksByGroupId(ctx context.Context, groupID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Content,
			&i.Status,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS(
    SELECT 1 FROM tasks WHERE id = $1
) AS exists
`

func (q *Queries) TaskExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTaskById = `-- name: UpdateTaskById :one
UPDATE tasks
SET
    content = $2,
    deadline = $3,
    status = $4
WHERE
    id = $1
RETURNING id, group_id, content, status, deadline, created_at, updated_at
`

type UpdateTaskByIdParams struct {
	ID       int64              `json:"id"`
	Content  string             `json:"content"`
	Deadline pgtype.Timestamptz `json:"deadline"`
	Status   TaskStatus         `json:"status"`
}

func (q *Queries) UpdateTaskById(ctx context.Context, arg UpdateTaskByIdParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskById,
		arg.ID,
		arg.Content,
		arg.Deadline,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Content,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
