// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 核心动态信息表，存储用户发布的文本内容。
type Moment struct {
	// 动态的唯一标识符（主键）。
	ID int64 `json:"id"`
	// 动态的主要文本内容。
	Content string `json:"content"`
	// 记录的创建时间戳（带时区）。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录的最后更新时间戳（带时区）。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 附件元数据表，记录上传文件的物理和逻辑信息。
type MomentAttachment struct {
	// 附件的唯一标识符（UUID），作为主键。
	ID pgtype.UUID `json:"id"`
	// 文件在对象存储服务（如S3/MinIO）中的唯一路径/键。
	ObjectKey string `json:"object_key"`
	// 视频或文档等文件的封面图在对象存储中的唯一路径/键。
	CoverObjectKey pgtype.Text `json:"cover_object_key"`
	// 文件的原始名称，用于向用户展示。
	OriginalName string `json:"original_name"`
	// 文件的MIME类型（如 image/jpeg），用于客户端正确渲染。
	MimeType string `json:"mime_type"`
	// 文件的字节大小。
	FileSize int64 `json:"file_size"`
	// 文件的MD5哈希值，可用于文件完整性校验和快速去重。
	Md5 string `json:"md5"`
	// 上传完成状态标记，TRUE表示文件已成功持久化到对象存储。
	Completed bool `json:"completed"`
	// 记录的创建时间戳（带时区）。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 动态与附件的多对多关联表，定义了附件在动态中的显示顺序。
type MomentAttachmentLink struct {
	// 关联记录的唯一标识符（主键）。
	ID int64 `json:"id"`
	// 关联的动态ID（外键，指向 moments.id）。
	MomentID int64 `json:"moment_id"`
	// 关联的附件ID（外键，指向 moment_attachments.id）。
	AttachmentID pgtype.UUID `json:"attachment_id"`
	// 附件在该动态中的显示顺序
	Position int16 `json:"position"`
}
