// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moment.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMoment = `-- name: CreateMoment :one
INSERT INTO moments
(content)
VALUES ($1)
RETURNING id, content, created_at, updated_at
`

func (q *Queries) CreateMoment(ctx context.Context, content string) (Moment, error) {
	row := q.db.QueryRow(ctx, createMoment, content)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMomentAttachment = `-- name: CreateMomentAttachment :one
INSERT INTO moment_attachments
(
    object_key,
    original_name,
    mime_type,
    file_size,
    md5
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, object_key, cover_object_key, original_name, mime_type, file_size, md5, completed, created_at
`

type CreateMomentAttachmentParams struct {
	ObjectKey    string `json:"object_key"`
	OriginalName string `json:"original_name"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	Md5          string `json:"md5"`
}

func (q *Queries) CreateMomentAttachment(ctx context.Context, arg CreateMomentAttachmentParams) (MomentAttachment, error) {
	row := q.db.QueryRow(ctx, createMomentAttachment,
		arg.ObjectKey,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSize,
		arg.Md5,
	)
	var i MomentAttachment
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.CoverObjectKey,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Md5,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMomentByID = `-- name: DeleteMomentByID :exec
DELETE FROM moments
WHERE id = $1
`

func (q *Queries) DeleteMomentByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMomentByID, id)
	return err
}

const getMomentByID = `-- name: GetMomentByID :one
SELECT id, content, created_at, updated_at FROM moments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMomentByID(ctx context.Context, id int64) (Moment, error) {
	row := q.db.QueryRow(ctx, getMomentByID, id)
	var i Moment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMoments = `-- name: ListMoments :many
SELECT id, content, created_at, updated_at FROM moments
WHERE ($1::timestamp IS NULL OR created_at < $1::timestamp)
ORDER BY created_at DESC
LIMIT $2
`

type ListMomentsParams struct {
	Column1 pgtype.Timestamp `json:"column_1"`
	Limit   int32            `json:"limit"`
}

func (q *Queries) ListMoments(ctx context.Context, arg ListMomentsParams) ([]Moment, error) {
	rows, err := q.db.Query(ctx, listMoments, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Moment
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const momentExists = `-- name: MomentExists :one
SELECT EXISTS(
    SELECT 1 FROM moments WHERE id = $1
) AS exists
`

func (q *Queries) MomentExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, momentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
